mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'mysite'
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('index', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('team/', views.team, name='team'),
    path('about/', views.about, name='about'),
    path('aerodynamics/', views.aerodynamics, name='aerodynamics'),
    path('vehicledynamics/', views.vehicledynamics, name='vehicledynamics'),
    path('electronics/', views.electronics, name='electronics'),
    path('powertrain/', views.powertrain, name='powertrain'),
    path('media/', views.media, name='media'),
    path('marketing/', views.marketing, name='marketing'),
    path('gallery/', views.gallery, name='gallery')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nitk_racing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls')),
    path('ev/', include('nitkracing_ev.urls'))
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

nitkracing_ev/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'nitkracing_ev'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('team/', views.team, name='team'),
    path('about/', views.about, name='about'),
    path('lv/', views.lv, name='lv'),
    path('chassis/',views.chassis, name='chassis'),
    path('vehicledynamics/', views.vehicledynamics, name='vehicledynamics'),
    path('battery/', views.battery, name='battery'),
    path('epowertrain/', views.epowertrain, name='epowertrain'),
    path('media/', views.media, name='media'),
    path('marketing/', views.marketing, name='marketing'),
    path('gallery/', views.gallery, name='gallery')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/models.py
from django.db import models


# Create your models here.
class Banner(models.Model):
    CHOICES = [(1, 'Home'), (2, 'About'), (3, 'Team'), (4, 'Contact'), (5, 'Aero'),
               (6, 'VD'), (7, 'PWR'), (8, 'ELEC'), (11, 'Gallery'), (10, 'Media'), (9, 'Marketing')]
    page_to_display = models.IntegerField(default=1, choices=CHOICES)
    bg_img = models.ImageField(upload_to='images/')
    small_text = models.CharField(max_length=50, blank=True)
    large_text = models.CharField(max_length=150)

    def __str__(self):
        return self.large_text


class Sponsor(models.Model):
    sponsor_name = models.CharField(max_length=250)
    category = models.CharField(max_length=250)
    img = models.ImageField(upload_to='images/sponsors')
    sponsor_link = models.URLField(default=" ")

    def __str__(self):
        return self.sponsor_name


# 12345678
class Member(models.Model):
    CHOICES = [(1, 'AERO'), (2, 'VD'), (3, 'PWR'), (4, 'ELEC'), (6, 'MEDIA'), (5, 'MARKETING')]
    roll_number = models.CharField(max_length=8, primary_key=True)
    priority = models.IntegerField(default=5,unique=False,choices=[(0,'cap'),(1,'op'),(2,'tech head'),(3,'subsytem head'),(4,'media/marketing'),(5,'other')])
    sig = models.IntegerField(default=0, choices=CHOICES)
    writeup = models.CharField(max_length=144, blank=True)
    member_name = models.CharField(max_length=50)
    post = models.CharField(max_length=300)
    insta = models.URLField(default="")
    linkdin = models.URLField(default="")
    email = models.EmailField(blank=True)
    member_img = models.ImageField(upload_to='images/members')
    sig_head = models.BooleanField(default=False)
    class Meta:
        ordering = ['priority']
    def __str__(self):
        return self.member_name


class Image(models.Model):
    img = models.ImageField(upload_to='images/')
    alt_text = models.CharField(max_length=50, blank=True)
    display_on_index = models.BooleanField()

    def __str__(self):
        return self.alt_text


class Blog(models.Model):
    title = models.CharField(max_length=200, unique=True)
    blog_filter = models.IntegerField(default=0, choices=[(1, 'AERO'), (2, 'VD'), (3, 'PWR'), (4, 'ELEC'), (6, 'MEDIA'),
                                                          (5, 'MARKETING')]
                                      )
    author = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title


class Document(models.Model):
    CHOICES = [(5,'INDEX'),(1, 'AERO'), (2, 'VD'), (3, 'PWR'), (4, 'ELEC')]
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='3dModels/')
    subsystem_filter = models.IntegerField(default=0, choices=CHOICES)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description


class Pitstop(models.Model):
    link = models.URLField(default="#")
    # Google_id = models.CharField(max_length=100,default=" ",blank=True,help_text="ignore maadi!!! <br> leave blank")
    edition = models.CharField(max_length=100, default=" ")
    created_on = models.DateTimeField()
    cover = models.ImageField(upload_to='pits', blank=True)

    class Meta:
        ordering = ['-created_on']


class Subscribers(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email


class about_us_content(models.Model):
    youtube_link= models.URLField()
    text_next_to_video=models.TextField()

mysite/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render

from .models import *


def landing_page(request):
    return render(request, 'landing_page.html')
    
def index(request):
    banners_list = Banner.objects.filter(page_to_display=1)
    sponsors_list = Sponsor.objects.all()
    sig_head_list = Member.objects.filter(sig_head=True)
    document_list = Document.objects.filter(subsystem_filter=5)
    image_gallery_full = Image.objects.all()
    image_gallery_short = Image.objects.filter(display_on_index=True)
    context = {'banners_list': banners_list,
               'sponsors_list': sponsors_list,
               'sig_head_list': sig_head_list,
               'image_gallery_full': image_gallery_full,
               'image_gallery_short': image_gallery_short,
               'document_list': document_list
               }
    return render(request, 'index_v1.html', context=context)


def about(request):
    sponsors_list = Sponsor.objects.all()
    banners_list = Banner.objects.filter(page_to_display=2)
    blog_list = Blog.objects.order_by('updated_on')[:3]
    sig_head_list = Member.objects.filter(sig_head=True)
    image_gallery_full = Image.objects.all()
    full_member_list = Member.objects.all()
    image_gallery_short = Image.objects.filter(display_on_index=True)
    document_list = Pitstop.objects.all()
    if(request.method=='POST'):
        subs = Subscribers(email=request.POST['mailid'])
        message ="Greetings from NITKRacing,\n enclosed below is a link to the latest editon of pitstop\n"
        message+=Pitstop.objects.all()[0].link
        message+="\nRegards NITKRacing"
        subs.save()
        send_mail('Thank you for subscribing!',
                      message,
                      settings.EMAIL_HOST_USER,
                      [subs.email],
                      fail_silently=False)
    context = {'banners_list': banners_list,
               'blog_list': blog_list,
               'sig_head_list': sig_head_list,
               'image_gallery_full': image_gallery_full,
               'image_gallery_short': image_gallery_short,
               'members_list': full_member_list,
               'sponsors_list': sponsors_list,
               'document_list': document_list
               }
    return render(request, 'about_v1.html', context=context)


def contact(request):
    sponsors_list = Sponsor.objects.all()
    banners_list = Banner.objects.filter(page_to_display=3)
    image_gallery_full = Image.objects.all()
    image_gallery_short = Image.objects.filter(display_on_index=True)
    context = {'banners_list': banners_list,
               'image_gallery_full': image_gallery_full,
               'sponsors_list': sponsors_list,
               'image_gallery_short': image_gallery_short
               }
    if(request.method=='POST'):
        message ="Name :"+ request.POST['usr']+"\n"+ "Email :" + request.POST['mailid']
        message += "\n" + "website :" + request.POST['website']
        message += "\n" + "Content :\n" + request.POST['msg']

        send_mail('Website Contact Form',
                      message,
                      settings.EMAIL_HOST_USER,
                      ['addhyanmalhotra@gmail.com','captain.nitkracing@gmail.com'],
                      fail_silently=False)

    return render(request, 'contact_v1.html', context=context)


def team(request):
    sponsors_list = Sponsor.objects.all()
    full_member_list = Member.objects.all()
    banners_list = Banner.objects.filter(page_to_display=4)
    sig_head_list = Member.objects.filter(sig_head=True)
    image_gallery_full = Image.objects.all()
    image_gallery_short = Image.objects.filter(display_on_index=True)
    context = {
        'sig_head_list': sig_head_list,
        'banners_list': banners_list,
        'image_gallery_full': image_gallery_full,
        'image_gallery_short': image_gallery_short,
        'full_member_list': full_member_list,
        'sponsors_list': sponsors_list
    }
    return render(request, 'team_v1.html', context=context)


def aerodynamics(request):
    sponsors_list = Sponsor.objects.all()
    full_member_list = Member.objects.filter(sig=1)
    blog_list = Blog.objects.filter(blog_filter=1)
    banners_list = Banner.objects.filter(page_to_display=5)
    document_list = Document.objects.filter(subsystem_filter=1)
    context = {'full_member_list': full_member_list,
               'banners_list': banners_list,
               'blog_list': blog_list,
               'sponsors_list': sponsors_list,
               'document_list': document_list
               }
    return render(request, 'aerodynamics_v1.html', context=context)


def vehicledynamics(request):
    sponsors_list = Sponsor.objects.all()
    full_member_list = Member.objects.filter(sig=2)
    blog_list = Blog.objects.filter(blog_filter=2)
    banners_list = Banner.objects.filter(page_to_display=6)
    document_list = Document.objects.filter(subsystem_filter=2)
    context = {'full_member_list': full_member_list,
               'banners_list': banners_list,
               'sponsors_list': sponsors_list,
               'blog_list': blog_list,
               'document_list': document_list
               }
    return render(request, 'vehicledynamics_v1.html', context=context)


def powertrain(request):
    sponsors_list = Sponsor.objects.all()
    full_member_list = Member.objects.filter(sig=3)
    blog_list = Blog.objects.filter(blog_filter=3)
    banners_list = Banner.objects.filter(page_to_display=7)
    document_list = Document.objects.filter(subsystem_filter=3)
    context = {'full_member_list': full_member_list,
               'banners_list': banners_list,
               'sponsors_list': sponsors_list,
               'blog_list': blog_list,
               'document_list': document_list
               }
    return render(request, 'powertrain_v1.html', context=context)


def electronics(request):
    sponsors_list = Sponsor.objects.all()
    full_member_list = Member.objects.filter(sig=4)
    blog_list = Blog.objects.filter(blog_filter=4)
    banners_list = Banner.objects.filter(page_to_display=8)
    document_list = Document.objects.filter(subsystem_filter=4)
    context = {'full_member_list': full_member_list,
               'banners_list': banners_list,
               'blog_list': blog_list,
               'sponsors_list': sponsors_list,
               'document_list': document_list
               }
    return render(request, 'electronics_v1.html', context=context)


def marketing(request):
    sponsors_list = Sponsor.objects.all()
    full_member_list = Member.objects.filter(sig=5)
    blog_list = Blog.objects.filter(blog_filter=5)
    banners_list = Banner.objects.filter(page_to_display=9)
    context = {'full_member_list': full_member_list,
               'banners_list': banners_list,
               'blog_list': blog_list,
               'sponsors_list': sponsors_list
               }
    return render(request, 'marketing_v1.html', context=context)


def media(request):
    sponsors_list = Sponsor.objects.all()
    full_member_list = Member.objects.filter(sig=6)
    blog_list = Blog.objects.filter(blog_filter=6)
    banners_list = Banner.objects.filter(page_to_display=10)
    context = {'full_member_list': full_member_list,
               'banners_list': banners_list,
               'blog_list': blog_list,
               'sponsors_list': sponsors_list
               }
    return render(request, 'media_v1.html', context=context)


def gallery(request):
    sponsors_list = Sponsor.objects.all()
    image_gallery_full = Image.objects.all()
    image_gallery_short = Image.objects.filter(display_on_index=True)
    banners_list = Banner.objects.filter(page_to_display=11)
    context = {'image_gallery_short': image_gallery_short,
               'image_gallery_full': image_gallery_full,
               'banners_list': banners_list,
               'sponsors_list': sponsors_list,
               }
    return render(request, 'gallery_v1.html', context=context)

mysite/templates/aerodynamics_v1.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

{% if blog_list.count %}
    <section class="blog-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 p-0">
                    <div class="blog-item">
                        {% for blog in blog_list %}
                            <div class="bi-text">
                                <h5>{{ blog.title }}</h5>
                                <ul>
                                    <li>{{ blog.author }}</li>
                                    <li>{{ blog.updated_on }}</li>
                                </ul>
                                <p>{{ blog.content }}</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endif %} 
<!-- 3d-->
<section class="gallery-section">
    <div class="section-title">
        <span style="font-size: 35px ;">A glimpse under the hood</span>
        <h2 style="font-size: 33px;">3D MODELS</h2>
    </div>
    <div class="gallery">
        <div class="grid-sizer"></div>
        <script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js"></script>
        <script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script>
        {% for document in document_list %}

            <model-viewer class="gs-item grid-wide" src="{{ document.document.url }}" alt="{{ document.description }} "
                          auto-rotate camera-controls>
            </model-viewer>

        {% endfor %}

    </div>
</section>
<!-- Teaam -->
<section class="team-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="team-title">
                    <div class="section-title">

                        <h2>MEET THE SQUAD</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="ts-slider owl-carousel">

                {% for member in full_member_list %}
                    <div class="col-lg-4">
                        <div class="ts-item set-bg" data-setbg="{{ member.member_img.url }}">
                            <div class="ts_text">
                                <h4>{{ member.member_name }}</h4>
                                <span>{{ member.post }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    </div>
</section>
<!-- substem select-->
{% include 'our_subsystems.html' %}
<!-- sponsors slider-->
<section class="testimonial-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <span>meet the support squad</span>
                    <h2>Our sponsors</h2>
                </div>
            </div>
        </div>
        <div class="ts_slider owl-carousel">
            {% for sponsor in sponsors_list %}
                <div class="ts_item">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="ti_pic"><a href="{{ sponsor.sponsor_link }}">
                                <img src="{{ sponsor.img.url }}" alt=""></a>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

{% block script %}

    <script>
        var selected_item = document.getElementById('nav-bar-subsystem');
        selected_item.classList.add('active');
    </script>

{% endblock %}

mysite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="eng">
    <head>
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500,600,700&display=swap" rel="stylesheet">

        <!-- CSS Styles -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
        <link rel="stylesheet" href="{% static 'css/barfiller.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
        <style>
            html{
                overflow-x: hidden;
            }
            #nav-bar{
                background-color: black;
            }
            .banner-text{
                position:relative; 
                top:-50vh;
                left: 60vw;
            }
            .owl-dot{
                z-index: auto;
                color: blue;
            }
            #nav-bar-subsystem{
                z-index:2000;
            }
            .nav-menu ul li a{
                font-size : 18px;
            }
            .footer-section *{
                color:white;
            }
            .slide-in{
                position: relative;
                animation-name: slide-in;
                animation-duration: 1s;
            }
            .margin-adder{
                height:10vh;
                width:100vw;
            }
            @keyframes slide-in{
                0%{
                    top:40px;
                }
                25%{
                    top:20px;
                }
                50%{
                    top:10px;
                }
                100%{
                    top:0px;
                }
            }
        </style>

        {% block head %}
        {% endblock %}
    </head>
    <body style="background-color: black;">
        <!-- Page Preloder -->
        <div id="preloder">
            <div class="loader"></div>
        </div>

        <div class="offcanvas-menu-overlay"></div>
            <div class="offcanvas-menu-wrapper">
                <div class="canvas-close">
                    <i class="fa fa-close"></i>
                </div>

                <nav class="canvas-menu mobile-menu">
                    <ul>
                        <li><a href="../index">Home</a></li>
                        <li><a href="../about">About Us</a></li>
                        <li><a href="../team">Our Team</a></li>
                        <li class="active"><a href="#">Subsystems</a>
                            <ul class="dropdown">
                                <li><a href="../aerodynamics">Aerodynamics</a></li>
                                <li><a href="../vehicledynamics">Vehicle Dynamics</a></li>
                                <li><a href="../powertrain">Powertrain</a></li>
                                <li><a href="../electronics">Electronics</a></li>
                                <li><a href="../media">Media</a></li>
                                <li><a href="../marketing">Marketing</a></li>
                            </ul>
                        </li>
                        <li><a href="../gallery">Gallery</a></li>
                        <li><a href="../contact">Contact</a></li>
                    </ul>

                </nav>
                <div id="mobile-menu-wrap"></div>
                <div class="canvas-social">
                    <a href="https://www.facebook.com/nitkracing"><i class="fa fa-facebook"></i></a>
                    <a href="https://www.linkedin.com/company/nitk-racing"><i class="fa fa-linkedin"></i></a>
                    <a href="https://www.youtube.com/channel/UCboCcz11TdW0tMa_5n-eiyA"><i class="fa fa-youtube-play"></i></a>
                    <a href="https://www.instagram.com/nitkracing/"><i class="fa fa-instagram"></i></a>
                </div>
            </div>

        <div class="container-fluid" id="nav-bar">
            <div class="row" style="display:flex; align-items: center;">
                <div class="col-lg-3">
                    <!--div class="logo"-->
                        <a class="navbar-brand" href="{% url 'mysite:index' %}">
                            <img src="{% static 'img/logo.png' %}" alt="">
                        </a>
                    <!---/div-->
                </div>
                <div class="col-lg-6">
                    <nav class="nav-menu">
                        <ul>
                            <li id="nav-bar-home"><a href="{% url 'mysite:index' %}">Home</a></li>
                            <li id="nav-bar-about"><a href="{% url 'mysite:about' %}">About Us</a></li>
                            <li id="nav-bar-team"><a href="{% url 'mysite:team' %}">Our Team</a></li>
                            <li id="nav-bar-subsystem"><a href="#">Subsystems</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'mysite:aerodynamics' %}">Aerodynamics</a></li>
                                    <li><a href="{% url 'mysite:electronics' %}">Electronics</a></li>
                                    <li><a href="{% url 'mysite:vehicledynamics' %}">Vehicle Dynamics</a></li>
                                    <li><a href="{% url 'mysite:powertrain' %}">Powertrain</a></li>
                                    <li><a href="{% url 'mysite:marketing' %}">Marketing</a></li>
                                    <li><a href="{% url 'mysite:media' %}">Media</a></li>
                                </ul>
                            </li>
                            <li id="nav-bar-gallery"><a href="{% url 'mysite:gallery' %}">Gallery</a></li>
                            <li id="nav-bar-contact"><a href="{% url 'mysite:contact' %}">Contact</a></li>
                            <li><a href="{% url 'nitkracing_ev:index' %}">EV Team</a></li>
                        </ul>

                    </nav>
                </div>
                <div class="col-lg-3">
                    <div class="top-option">
                        <div class="to-social">
                            <a href="https://www.facebook.com/nitkracing" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="https://www.linkedin.com/company/nitk-racing" target="_blank"><i class="fa fa-linkedin"></i></a>
                            <a href="https://www.youtube.com/channel/UCQ2hGaTidBqanu5chivRTsQ" target="_blank"><i
                                    class="fa fa-youtube-play"></i></a>
                            <a href="https://www.instagram.com/nitkracing/" target="_blank"><i class="fa fa-instagram"></i></a>
                            <a href="https://twitter.com/nitkracing?lang=en" target="_blank"><i class="fa fa-twitter"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="canvas-open" style="z-index: 30;">
                <i class="fa fa-bars"></i>
            </div>
        </div>

        <div id="center-banner" style="z-index:-2000;">
            <div class="owl-carousel owl-banner">
                {% for banner in banners_list%}
                    <div class="banner-img" id="banner-{{forloop.counter}}" style="width:100vw;" data-id="{{forloop.counter}}">
                        <img src="{{ banner.bg_img.url }}" style="width:100vw; height:100%;">
                        <div class="banner-text" id="banner-text-{{forloop.counter}}" style="color:white;">
                            <span class='slide-in' style="color:white;">{{ banner.small_text }}</span>
                            <h1 class='slide-in' style="color:white;">{{ banner.large_text }}</h1>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        {% block body %}
        {% endblock %}

        <!-- Get In Touch Section Begin -->
        <section class="footer-section">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="fs-about">
                            <div class="logo">
                                <a href="../">
                                    <img src="{% static 'img/logo.png' %}" alt="">
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="gt-text">
                            <a target="__blank" href="https://www.google.com/maps/dir//National+Institute+of+Technology,+Karnataka/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x3ba35211b768ac8f:0x6b1144ac2d5dadf3?sa=X&ved=2ahUKEwiJx4SN1NTrAhXF8XMBHXhYADoQ9RcwGHoECBAQBA">
                            <i class="fa fa-map-marker"></i></a>
                            <p><a target="__blank" href="https://www.google.com/maps/dir//National+Institute+of+Technology,+Karnataka/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x3ba35211b768ac8f:0x6b1144ac2d5dadf3?sa=X&ved=2ahUKEwiJx4SN1NTrAhXF8XMBHXhYADoQ9RcwGHoECBAQBA">
                                National Institute of Technology<br> NH 66, Srinivasnagar, Surathkal<br> Mangalore
                                Karnataka <br>
                                575025</a></p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="gt-text">
                            <a href="tel:7259159980"><i class="fa fa-mobile"></i></a>
                            <ul>
                                <li><a href="tel:7259159980">7259159980</a></li>
                                <li><a href="tel:7259159980">9113514266</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="gt-text email">
                            <a href="mailto:captain.nitkracing@gmail.com"><i class="fa fa-envelope"></i></a>
                            <p><a href="mailto:captain.nitkracing@gmail.com">captain.nitkracing@gmail.com</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12 text-center">
                    <div class="copyright-text">
                        <p>Developed and maintained by <strong>Addhyan Malhotra</strong> & <strong>Harshal
                            Shende</strong></p>
                    </div>
                </div>
            </div>
        </section>
    </body>

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'js/jquery.barfiller.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script>
        var owl = $('.owl-carousel');

        $(document).ready(function(){
            owl.owlCarousel({
                autoplay:true,
                autoplayTimeout:5000,
                dots : true, 
                autoWidth:true,
                items:1,
                onTranslated: function(){
                    var id=$('.owl-item.active .banner-img').data('id');
                    $(".banner-text").hide()
                    $("#banner-text-"+id).hide().fadeIn(2000, function() {})
                },
            });
            $(".banner-text").hide()
            $("#banner-text-1").hide().fadeIn(2000, function() {})
        });
        
    </script>
    {% block script %}
    {% endblock %}

</html>